const listaDePersonagens = [
  // "Aarao",
  // "Abednego",
  // "Abel",
  // "Abias",
  // "Abiatar",
  // "Abigail",
  // "Abimeleque",
  // "Abimeleque",
  // "Abimeleque",
  // "Abinadabe",
  // "Abisai",
  // "Abner",
  // "Abraao",
  // "Absalao",
  // "Aca",
  // "Acabe",
  // "Acaz",
  // "Acazias",
  // "Acsa",
  // "Adoni-Bezeque",
  // "Adonias",
  // "Agabo",
  // "Agague",
  // "Ageu",
  "Agripa-1",
  "Agripa-2",
  "Aias",
  // "Aicao",
  // "Arao",
  // "Jeremias",
  // "Maer-Salal-Has-Baz",
  // "Maria-Madalena"
];
